### ISSUE TITLE
Problemas na conexão.

### ISSUE THREAD

**Issue by flaviolicorio** [tem-cafe/api-tem-cafe#5]
@Maransatto estou com problemas. Acredito que seja na conexão com o banco. O sr. consegue me ajudar?
Alterações estão no branch implementandoAPI

**Comment by Maransatto** [comment]
@flaviolicorio 
Dei uns commits pra corrigir umas nomenclaturas.
Não deu tempo ainda de ver, vamos ver se na hora da aula eu consigo

**Comment by flaviolicorio** [comment]
@Maransatto valeu!

**Comment by flaviolicorio** [comment]
Corrigi. Era burrice minha! não estava chamando o banco kkkk
